import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import { MusicPlayer } from "../components/MusicPlayer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Music Player</h1>
        <MusicPlayer />
      </main>
    </div>
  );
}
